### ISSUE TITLE
Can not load the dog config correctly.

### ISSUE THREAD

**Issue by tedzhang2891** [ajacobson/chiadog-docker#4]
```shell 
babybear@chiah001:~$ ls ~/.chiadog/
config.yaml
````

```shell
babybear@chiah001:~$ sudo docker run --name chiadog -d -it artjacobson/chiadog-docker:latest /bin/sh -v /home/babybear/.chiadog:/root/.chiadog -v /home/babybear/.chia/mainnet/log:/root/.chia/mainnet/log:ro -e TZ="Asia/Shanghai"
8c6a52dd2a6b98ecf994a67a1695fa68eed4aff774642ff904211230bdbc104b
babybear@chiah001:~$ sudo docker logs chiadog
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    config = Config(Path(args.config))
  File "/chiadog/src/config.py", line 14, in __init__
    raise ValueError(f"Invalid config.yaml path: {config_path}")
ValueError: Invalid config.yaml path: /root/.chiadog/config.yaml
```

could you help to figure out where are wrong?

**Comment by asaphaaning** [comment]
@tedzhang2891 You need to put the -v mounts before the image parameter, e.g.

```
docker run --name chiadog -v /host/path:/root/.chiadog -v /host/path/mainnet/log:/root/.chia/mainnet/log:ro -d artjacobson/chiadog-docker:latest
```

**Comment by tedzhang2891** [comment]
@ASAPHAANING your solution worked for me and thank you.
